# Generated by Django 3.1 on 2021-04-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210411_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField()),
                ('last_request', models.DateTimeField()),
            ],
        ),
    ]
